# fly.toml app configuration file generated for celedrive on 2024-06-08T00:09:08+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'celedrive'
primary_region = 'iad'

[build]

[env]
  PORT = '3333'

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
